const router = require('express').Router()
const assignments = require('../Controllers/assignments')
const path = require('path');
const upload = require('../Middleware/uploadFile')
const token = require('../Middleware/token')

router.get('/list-assignments/:id',token,assignments.list_assignments)
router.get('/page-post-assignments/:id',token,assignments.page_post_assignments)
router.get('/detail-assignment/:assignmentId',token,assignments.detail_assignment)
router.get('/verified-assignment/:assignmentId',token,assignments.verified_assignment)
router.get('/all-up-comming/:id',token,assignments.all_up_comming)
router.get('/all-past-due/:id',token,assignments.all_past_due)
router.get('/all-completed/:id',token,assignments.all_completed)
router.get('/up-comming/:id/:id_classroom',token,assignments.up_comming)
router.get('/past-due/:id/:id_classroom',token,assignments.past_due)
router.get('/completed/:id/:id_classroom',token,assignments.completed)
router.get('/activity/:id/',token,assignments.activity)
router.get('/activity-group/:id/',token,assignments.activity_group)
router.get('/activity-teacher/:id/',token,assignments.activity_teacher)
router.post('/add-assignment',token,upload.any(),assignments.add_assignments)
router.post('/delete-assignment',token,assignments.delete_assignment)
router.post('/update-assignment',token,upload.any(),assignments.update_assignment)
router.get('/assignments/:id_assignment/:workId/file/:fileName',assignments.check_type_file)
router.get('/size-files-assignments/:id_assignment/:id',assignments.get_file_size)
router.get('/data-assignment/:id_assignment',token,assignments.data_assignment)
router.post('/delete-sheet',assignments.delete_sheet)
router.get('/remember-groups/:classroomId',token,assignments.remember_groups)
module.exports = router


