const router = require('express').Router()
const express = require('express')
const classroom = require('../Controllers/classroom')
const token = require('../Middleware/token')

router.post('/add-classroom',token,classroom.add_classroom)
router.get('/add-classroom/:id',token,classroom.display_classroom)
router.post('/check-classroom-access',token,classroom.check_classroom_access)
router.post('/check-work-access',token,classroom.check_work_access)
router.post('/check-full-work-access',token,classroom.check_full_work_access)
router.post('/check-detail-assignment',token,classroom.check_detail_assignment)
router.post('/re-code',token,classroom.re_code)
router.get('/joined-classroom/:id',token,classroom.joined_classroom)
router.get('/detail_classroom/:id',token,classroom.detail_classroom)
router.get('/teacher/:id',token,classroom.teacher)
router.post('/join-classroom',token,classroom.join_classroom)
router.get('/members/:id',token,classroom.members)
router.delete('/delete-member',token,classroom.delete_member)
router.post('/leave-classroom',token,classroom.leave_classroom)
router.post('/update-classroom',token,classroom.update_classroom)
router.get('/all-members',token,classroom.all_members)
router.get('/all-classroom',token,classroom.all_classroom)
router.post('/delete-classroom',token,classroom.delete_classroom)
router.post('/add-number-teacher',token,classroom.add_teacher)
router.get('/data-number-teacher',token,classroom.data_number_teacher)
router.post('/delete-number-teacher',token,classroom.delete_number_teacher)

module.exports = router;