const router = require('express').Router()
const works = require('../Controllers/works')
const upload = require('../Middleware/uploadFile')
const token = require('../Middleware/token')

router.get('/detail-work/:work_id/:user_id',token,works.detail_work)
router.get('/page-post-work/:id/:id_user',token,works.page_post_works)
router.get('/assignments/:id_assignment/:workId/:id_user/:fileName',works.open_file_work)
router.get('/size-files-work/:workId',works.get_file_size)
router.get('/my-work/:work_id/:user_id',token,works.my_work)
router.post('/send-work',token,upload.any(),works.send_work)
router.post('/cancel-work',token,works.cancel_work)
router.post('/delete-work',token,works.delete_work)
router.get('/get-comment-work/:id_work/:id_user',token,works.get_comment_work)
router.post('/add-comment-work',token,works.add_comment_work)
router.post('/update-feedback',token,works.update_feedback)
router.get('/get-scores/:id_assignment',token,works.get_score)
router.get('/count-activity/:user_id',token,works.count_activity)
router.get('/count-teacher-activity/:user_id',token,works.count_teacher_activity)
router.post('/update-activity',token,works.update_activity)
router.post('/update-status-teacher',token,works.update_teacher_activity)
router.post('/update-status-activity',token,works.update_state_activity)
router.post('/update-status-teacher-activity',token,works.update_state_teacher_activity)

module.exports = router