const router = require('express').Router()
const express = require('express')
const classroom = require('../Controllers/classroom')

router.post('/add-classroom',classroom.add_classroom)
router.get('/add-classroom/:id',classroom.display_classroom)
router.post('/check-classroom-access',classroom.check_classroom_access)
router.post('/check-work-access',classroom.check_work_access)
router.post('/check-full-work-access',classroom.check_full_work_access)
router.post('/check-detail-assignment',classroom.check_detail_assignment)
router.post('/re-code',classroom.re_code)
router.get('/joined-classroom/:id',classroom.joined_classroom)
router.get('/detail_classroom/:id',classroom.detail_classroom)
router.get('/teacher/:id',classroom.teacher)
router.post('/join-classroom',classroom.join_classroom)
router.get('/members/:id',classroom.members)
router.delete('/delete-member',classroom.delete_member)
router.post('/leave-classroom',classroom.leave_classroom)
router.post('/update-classroom',classroom.update_classroom)
router.get('/all-members',classroom.all_members)
router.get('/all-classroom',classroom.all_classroom)
router.post('/delete-classroom',classroom.delete_classroom)
router.post('add-number-teacher',classroom.add_classroom)

module.exports = router;